Repository AY2021S1-CS2113T-T12-4/tp, pull requests merged in 2020-10, with the labels that each got.

#35 Branch repeatcommand
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/EventList.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
Labels: priority.High, type.Story

#43 Branch support indiv repeat
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/event/DateStatusPair.java
  src/main/java/seedu/duke/event/Event.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
Labels: priority.High, type.Task

#58 Branch repeat exception handling
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/event/Repeat.java
  src/main/java/seedu/duke/exception/DukeException.java
  src/main/java/seedu/duke/exception/InvalidTimeUnitException.java
  src/main/java/seedu/duke/exception/MissingDeadlineRepeatException.java
  src/main/java/seedu/duke/exception/WrongNumberOfArgumentsException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
Labels: priority.High, type.Task

#70 Branch assert
  src/main/java/seedu/duke/event/Repeat.java
Labels: priority.Low, priority.Medium, type.Task

#71 Branch add check assertions
  src/main/java/seedu/duke/command/CheckCommand.java
Labels: priority.Medium, type.Task

#87 Branch file system
  data/goal.txt
  data/personal.txt
  data/timetable.txt
  data/zoom.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/Timetable.java
  src/main/java/seedu/duke/event/Zoom.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/CheckCommandTest.java
  src/test/java/seedu/duke/command/DeadlineCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  storagetester/goal.txt
  storagetester/personal.txt
  storagetester/timetable.txt
  storagetester/zoom.txt
  storagetestermodelans/goal.txt
  storagetestermodelans/personal.txt
  storagetestermodelans/timetable.txt
  storagetestermodelans/zoom.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, type.Task

#101 Branch save command fix
  data/goal.txt
  data/personal.txt
  data/timetable.txt
  data/zoom.txt
  goalStoreTest/goal.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/DeadlineCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/test/java/seedu/duke/command/GoalCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Medium, type.Bug

#107 Reminder Command duplicate bug resolved
  data/personal.txt
  data/timetable.txt
  data/zoom.txt
  src/main/java/seedu/duke/Duke.java
Labels: priority.High, severity.Medium, type.Bug

#108 Fix a bug
  src/main/java/seedu/duke/command/CheckCommand.java
Labels: severity.High, type.Bug

#111 Branch fixgoalsave
  data/goal.txt
  src/main/java/seedu/duke/storage/Storage.java
Labels: priority.Medium, severity.Medium, type.Bug

#112 Update repeat to clear repeatEventList of events before cloning
  src/main/java/seedu/duke/command/RepeatCommand.java
Labels: type.Bug

#115 Update calendar to fix issue
  src/main/java/seedu/duke/command/CalendarCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/CalendarCommandTest.java
Labels: priority.High, severity.High, type.Bug

#119 Change order of format taken for dates
  src/main/java/seedu/duke/command/CheckCommand.java
Labels: severity.Medium, type.Bug

#120 Branch done undone command
  src/main/java/seedu/duke/command/DoneCommand.java
  src/main/java/seedu/duke/command/UndoneCommand.java
Labels: priority.Medium

#121 Branch help
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/exception/InvalidHelpTopicException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/ui/Ui.java
  src/main/resources/helpfile.txt
Labels: priority.Medium, type.Story

#124 Update developer guide with user stories and command section
  docs/DeveloperGuide.md
  docs/diagrams/Command.jpg
Labels: priority.High, type.Task

#136 Updated the correct Command image
  docs/diagrams/Command.jpg
Labels: priority.High, type.Task

#134 Implement note command
  src/main/java/seedu/duke/command/NoteCommand.java
  src/main/java/seedu/duke/data/UserData.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/java/seedu/duke/ui/Ui.java
  storagetester/personal.txt
  storagetester/timetable.txt
  storagetester/zoom.txt
  storagetestermodelans/personal.txt
  storagetestermodelans/timetable.txt
  storagetestermodelans/zoom.txt
Labels: priority.High, type.Story

#139 Branch note enhance
  src/main/java/seedu/duke/command/NoteCommand.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Medium, severity.Low, type.Enhancement

#142 Implement junit for note command
  src/test/java/seedu/duke/command/NoteCommandTest.java
Labels: priority.High, type.Task

#152 Update user guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#154 Update tables
  docs/UserGuide.md
Labels: priority.High, type.Task

#156 Branch user guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#159 Fixing table
  docs/UserGuide.md
Labels: priority.High, type.Task

#160 Branch user guide v2
  docs/UserGuide.md
Labels: priority.High, type.Task

#161 Update user guide with list, calendar and goal
  docs/UserGuide.md
Labels: priority.High, type.Task
