Repository AY2021S1-CS2113T-T12-4/tp, pull requests merged in 2020-11, with the labels that each got.

#223 Branch fix repeat time
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/exception/MissingRepeatListException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
Labels: priority.High, severity.High, type.Bug

#145 Branch multi parse command
  mainTest/personal.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.Medium, type.Enhancement, type.Story

#226 Add PPP Colin
  docs/team/colinNg.md
Labels: priority.High, type.Task

#225 Branch manual save command
  mainTest/personal.txt
  src/main/java/seedu/duke/command/SaveCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.Medium, type.Task

#230 Added PPP Qing Ning
  docs/AboutUs.md
  docs/team/lowqingning.md
  docs/team/ninggggx99.md
Labels: type.Task

#228 Fixes the PED bugs assigned in UG
  docs/UserGuide.md
Labels: severity.Low, type.Task

#232 Fix PPP link
  docs/AboutUs.md
Labels: type.Bug

#233 Update PPP
  docs/AboutUs.md
  docs/team/Reinbowl.md
  docs/team/marcusng.md
Labels: priority.High, type.Task

#234 Update AboutUs portfolio link
  docs/AboutUs.md
Labels: priority.High, type.Task

#240 fixing deadline with time parser
  src/main/java/seedu/duke/command/DeadlineCommand.java
  src/main/java/seedu/duke/parser/DateTimeParser.java
Labels: priority.High, type.Bug

#241 Symbol Change
  docs/UserGuide.md
  mainTest/personal.txt
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/CalendarCommandTest.java
  src/test/java/seedu/duke/command/CheckCommandTest.java
  src/test/java/seedu/duke/command/DeadlineCommandTest.java
  src/test/java/seedu/duke/command/ExtractCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/ReminderCommandTest.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: priority.Medium, severity.Low, type.Bug

#245 Enhancement for Notes
  src/main/java/seedu/duke/command/NoteCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/NoteCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: priority.High, type.Task

#246 Branch fixing issues
  docs/UserGuide.md
  src/main/java/seedu/duke/command/CheckCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/DoneCommand.java
  src/main/java/seedu/duke/command/UndoneCommand.java
  src/main/java/seedu/duke/exception/MissingSemicolonException.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.Medium, severity.Medium, type.Bug, type.Task

#248 Branch logging v1
  .gitignore
  datalogging.txt
  goalStoreTest/goal.txt
  mainTest/personal.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/EventLogger.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/storagetester/goal.txt
  src/test/storagetester/personal.txt
  src/test/storagetester/timetable.txt
  src/test/storagetester/zoom.txt
  src/test/storagetestermodelans/goal.txt
  src/test/storagetestermodelans/personal.txt
  src/test/storagetestermodelans/timetable.txt
  src/test/storagetestermodelans/zoom.txt
Labels: priority.High, type.Task

#250 Update Ui and relevant JUnit tests
  .gitignore
  src/main/java/seedu/duke/command/CalendarCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/command/CalendarCommandTest.java
  src/test/java/seedu/duke/command/CheckCommandTest.java
  src/test/java/seedu/duke/command/GoalCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/ReminderCommandTest.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, type.Bug

#253 Branch repeat date print
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/RepeatCommandTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: priority.Low, type.Task

#254 Branch markdown User Guide change
  docs/UserGuide.md
Labels: priority.High, severity.VeryLow, type.Bug

#255 Update developer guide with calendar feature
  docs/DeveloperGuide.md
  docs/diagrams/ListExecuteSequenceDiagram.jpg
Labels: priority.High, type.Task

#256 Fixed error that is caused when event without time is compared
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/command/ReminderCommandTest.java
Labels: priority.High, severity.High, type.Task

#258 Add logging for Deadline, Note, Reminder, View
  src/main/java/seedu/duke/command/DeadlineCommand.java
  src/main/java/seedu/duke/command/NoteCommand.java
  src/main/java/seedu/duke/command/ReminderCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/data/UserData.java
  src/main/java/seedu/duke/event/EventList.java
  src/test/java/seedu/duke/command/DeadlineCommandTest.java
Labels: priority.High, type.Task

#260 Branch helpfileupdate
  docs/UserGuide.md
  src/main/resources/helpfile.txt
Labels: priority.High, severity.Low, type.Task

#261 Updated the user guide
  docs/UserGuide.md
Labels: priority.High, type.Task

#263 Updating View command in UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#266 Update developer guide with diagrams
  docs/DeveloperGuide.md
  docs/diagrams/CalendarClassDiagram.png
  docs/diagrams/CalendarExecuteSequenceDiagram.jpg
  docs/diagrams/GoalClassDiagram.png
  docs/diagrams/GoalParseSequenceDiagram.jpg
  docs/diagrams/ListClassDiagram.png
Labels: priority.Medium, type.Task

#265 Branch save timetable fix
  src/main/java/seedu/duke/storage/StorageParser.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/storagetester/timetable.txt
  src/test/storagetestermodelans/timetable.txt
Labels: priority.High, severity.Medium, type.Bug

#269 Branch logging repeat
  src/main/java/seedu/duke/EventLogger.java
  src/main/java/seedu/duke/command/RepeatCommand.java
Labels: priority.High, severity.VeryLow, type.Bug

#273 Update javadoc
  src/main/java/seedu/duke/command/CalendarCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/data/UserData.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/EventList.java
  src/main/java/seedu/duke/event/Personal.java
  src/main/java/seedu/duke/event/Timetable.java
  src/main/java/seedu/duke/event/Zoom.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Medium, type.Task

#274 Add logging for calendar, goal, list commands
  src/main/java/seedu/duke/command/CalendarCommand.java
  src/main/java/seedu/duke/command/GoalCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
Labels: priority.Medium, type.Task

#276 Update list junit testing
  src/test/java/seedu/duke/command/ListCommandTest.java
Labels: priority.Medium, type.Task

#277 Branch colin java doc
  src/main/java/seedu/duke/EventLogger.java
  src/main/java/seedu/duke/command/ByeCommand.java
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.Medium, type.Task

#279 Update for developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeadlineSequenceDiagram.jpg
  docs/diagrams/DeadlineSequenceDiagram.png
  docs/diagrams/NoteCommandScenario.png
  docs/diagrams/NoteCommandSequenceDiagram.png
  docs/diagrams/ReminderCommandClass.png
  docs/diagrams/ReminderCommandSequenceDiagram.png
  docs/diagrams/ViewCommandClass.png
  docs/diagrams/ViewCommandSequenceDiagram.png
  src/main/java/seedu/duke/command/NoteCommand.java
Labels: priority.High, type.Task

#281 Fixing tiny errors
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#286 Fixed Deadline range and junit for date time
  docs/DeveloperGuide.md
  logging.txt.1
  logging.txt.1.lck
  logging.txt.2
  logging.txt.2.lck
  logging.txt.3
  logging.txt.3.lck
  logging.txt.4
  logging.txt.4.lck
  logging.txt.lck
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/CheckCommand.java
  src/main/java/seedu/duke/command/DeadlineCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/DoneCommand.java
  src/main/java/seedu/duke/command/UndoneCommand.java
  src/main/java/seedu/duke/exception/DateErrorException.java
  src/main/java/seedu/duke/exception/InvalidEventDateException.java
  src/main/java/seedu/duke/exception/TimeErrorException.java
  src/main/java/seedu/duke/parser/DateTimeParser.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/CheckCommandTest.java
  src/test/java/seedu/duke/command/DeadlineCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/DoneCommandTest.java
  src/test/java/seedu/duke/command/UndoneCommandTest.java
Labels: priority.High, type.Task

#285 Branch save fix
  src/main/java/seedu/duke/exception/InvalidStatusException.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/test/java/seedu/duke/storage/StorageTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug

#288 Removed Logging files
  .gitignore
  logging.txt.1
  logging.txt.1.lck
  logging.txt.2
  logging.txt.2.lck
  logging.txt.3
  logging.txt.3.lck
  logging.txt.4
  logging.txt.4.lck
  logging.txt.lck
Labels: priority.High, type.Task

#291 Error message with format
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/command/DeadlineCommand.java
  src/main/java/seedu/duke/command/NoteCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
Labels: priority.High, type.Task

#293 Update user guide
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#292 Branch help wrap and exception
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/duke/command/HelpCommand.java
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/exception/NumberOverflowException.java
  src/main/resources/helpfile.txt
Labels: priority.Medium, severity.Low, type.Bug

#295 Update PPP
  docs/team/reinbowl.md
Labels: priority.High, type.Task

#296 Add page break to PPP
  docs/team/reinbowl.md
Labels: priority.Medium, type.Task

#297 Add page breaks in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#299 Update page break in DG
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Task

#298 Update UG
  docs/UserGuide.md
Labels: priority.High, type.Task

#301 Update PPP
  docs/team/reinbowl.md
Labels: priority.Medium, type.Task

#300 Branch set repeat status
  src/main/java/seedu/duke/command/RepeatCommand.java
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/java/seedu/duke/ui/Ui.java
Labels: priority.High, severity.Medium, type.Bug

#303 Update page break in UG
  docs/UserGuide.md
Labels: priority.Medium, type.Task

#307 Fixing Diagrams and adding table for arguments
  docs/DeveloperGuide.md
  docs/diagrams/Command.jpg
  docs/diagrams/Command.png
  docs/diagrams/ReminderCommandClass.png
  docs/diagrams/ReminderCommandSequenceDiagram.jpg
  docs/diagrams/ReminderCommandSequenceDiagram.png
  docs/diagrams/ViewCommandClass.png
Labels: priority.High, type.Task

#305 Branch add command fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandClassDiagram.jpg
  docs/diagrams/ExtractCommandClassDiagram.jpg
  src/main/java/seedu/duke/command/AddCommand.java
  src/main/java/seedu/duke/command/ExtractCommand.java
Labels: priority.High

#309 Fixing Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DeadlineScenario.jpg
  docs/diagrams/DeadlineScenario.png
  docs/diagrams/NoteCommandScenario.png
Labels: priority.High, type.Task

#311 Added new features
  docs/team/ninggggx99.md
Labels: priority.High, type.Task

#315 Minor changes made to DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#317 PPP update jar version
  docs/team/ninggggx99.md
Labels: priority.High, type.Task

#319 Update Junit with testing for invalid date range
  src/test/java/seedu/duke/command/DeadlineCommandTest.java
Labels: priority.High, type.Task

#320 Branch developer guide v1
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/object_diagram_storage_after.png
  docs/diagrams/object_diagram_storage_before.png
  docs/team/colin386.md
  src/main/java/seedu/duke/storage/StorageParser.java
  src/main/resources/helpfile.txt
Labels: priority.Medium, type.Task
